### ISSUE TITLE
does not work with Win10 ATM

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/AnimeBuddy#6]
AnimeBuddy seems to not work ATM with Win10.
it opens up, you can see the logo and its just frozen there and then it closes/crashes..... just a heads up.

**Comment by AreFinstad** [comment]
seems to have fixed itself with updates of windows itself. works now, i know alot of older apps had issues at the start.

**Comment by jmediamanager** [comment]
Yeah it works for me.
NOTE - AnimeBuddy is not fully compatible with JMM Server, so I still need to do some fixes

**Comment by AreFinstad** [comment]
yeah, ATM i can't log in at all sadly :C Anime Buddy is just better with W10 IMO because of the mouse support for that side of windows.

also, i dont have the app icon in my taskbar when i use it like many other apps.

**Comment by jmediamanager** [comment]
Yeah, I have a surface and would really like to use it.
Just wish there was some good video streaming code out there I could use

**Comment by AreFinstad** [comment]
yeah, i did notice that there is alot of Anime Streaming apps at the store, is something like that you thought about? would be great to have it auto search for trailers and such for us tho and just have it as an info app.

**Comment by jmediamanager** [comment]
I mean I wanted to support streaming of videos from your own collection like Plex does.
That way you could use JMM Desktop or Anime Buddy
- When you are out travelling somewhere away from home
- Allow your friends/family access to your collection as well

But I also have an issue to allow linking of series to youtube videos / crunchrolly etc
So that way you could possibly use these apps without always needing to downloading vids

**Comment by AreFinstad** [comment]
ah, yeah ofc. didnt think about that. yeah that would be great. with codecs so we dont need transcoding also.

**Comment by AreFinstad** [comment]
if we had something like that in the app i would prob start using it for the UI only TBH.... it could be better tho, but i just find the character info so handy and we are missing that in the JMM client ATM
